### PR TITLE
Documenting moreText under 'meta', adjacent to "more at" options

### PR DESCRIPTION
**Pull request by talsraviv**

### CODE REVIEW

**Comment by talsraviv** [comment]
@sdougbrown @moollaza double check that my code sample is correct. 

I have `moreText` nested under `options` and not directly under `meta`, but wondering if that's accurate since all other properties are directly under `meta`

**Comment by moollaza** [comment]
@talsraviv unfortunately I can't get it to work like that. I can only get it to work when it's defined in `templates.options`.

I suppose that’s alright as we enable/disable the `moreAt` there?

**Comment by talsraviv** [comment]
I strongly believe it should be in meta... the docs are just a reflection of the actual logic, and it's pretty clear how it fits smoothly in meta and awkward in templates.options 

If it's any consolation, it's easier to get it to change now than later.

**Comment by moollaza** [comment]
@sdougbrown can you please clarify how the metaText can be defined?

Will it only work if it's specified inside `templates.options`? Or can we update it to be defined in the `meta` block. I wasn't able to get it to work that way...

**Comment by sdougbrown** [comment]
It should be possible to define in meta.options - I'll test and get back to you.

**Comment by moollaza** [comment]
> It should be possible to define in meta.options - I'll test and get back to you.

Awesome! Thanks.

**Comment by sdougbrown** [comment]
Okay yeah I just confirmed - it works fine under `meta.options`.

**Comment by talsraviv** [comment]
Alright - that's how it was documented in the draft, no add'l commits necessary. @moollaza take a final look?

**Comment by moollaza** [comment]
@talsraviv one final change, the input can actually be a String, Object (for URLs) or Array of both to support multiple item, separated with our usual `|` style separator.

It functions the same as the altSubtitle in the Icon template (because in the backend we pass the input to the same function)

Example
```js
moreText: [
    { href: 'https://yahoo.com', text: 'Yahoo Website' },
    { href: 'https://nytimes.com', text: 'NYT Website' },
    'Plain Text'
]
```

Creates: More at Foo | [Yahoo](http://yahoo.com) | [NYT](https://nytimes.com) | Plain Text

**Comment by talsraviv** [comment]
@moollaza updated

I just realized - is this possibly the only `meta` property that's nested under `options`? Everything else is directly under `meta`. 

Up to you guys, right now it's ready to merge. Let me know if you want to change it or just move on.

**Comment by moollaza** [comment]
@talsraviv I think there was a misunderstanding between me and Doug. It looks like specifying it under the `meta` property does *not* work. It actually only works when specified under `templates.options` -- in the backend this gets turned into `meta.options` (hence the confusion).

Let's change it back to how it was, where it's nested under `templates.options`. I can see it belonging under either the meta or the templates.options block, but for now let's just document it an move on. I don't expect it'll be used too often, right now there's only 3 or 4 IA's I can think of.

Sorry about the confusion.

**Comment by talsraviv** [comment]
@moollaza cool - check it out

**Comment by moollaza** [comment]
LGTM :+1:

**Pull request merged**
