### PR TITLE
Added page and links for video tutorials

### PR DESCRIPTION
**Pull request by tagawa**

### CODE REVIEW

**Comment by moollaza** [comment]
LGTM :+1: 

@talsraviv any thoughts?

**Comment by jagtalon** [comment]
:heart: :ok_hand:

**Comment by tagawa** [comment]
Thanks @moollaza but the images are not displaying for me at https://duck.co/duckduckhack/video-tutorials
Is there a problem with the images or is it my markdown?

**Comment by talsraviv** [comment]
This is great! I made tiny changes right on master (linked the images etc)

https://github.com/duckduckgo/duckduckgo-documentation/commit/da488c463ba5c9975c6e67b0437ef7a7f6fb2359

**Comment by tagawa** [comment]
Thanks. Looks like it's not possible to link the images themselves but thanks for putting the text links in.

**Comment by moollaza** [comment]
@talsraviv, we can't make the images into links. Daniel tried it but I had to remove it because our markdown parser can't figure it out. I  tried with raw HTML as well so well either have to skip the images or remove the links around them.

**Comment by talsraviv** [comment]
Gotcha - fixed on master. My bad. Looks good to have the images there either way.

**Pull request merged**
