### PR TITLE
Adding "use strict"

### PR DESCRIPTION
**Pull request by javathunderman**
Opening a PR on the goodies side of things soon. 

@moollaza

### CODE REVIEW

**Comment by moollaza** [comment]
@javathunderman it's much more involved than this :) -- Everything else in the doc needs to be updated so that the line numbers are correct and the examples are all correct as well.

**Comment by javathunderman** [comment]
@moollaza Didn't even think about that. *facepalm*

Anyway, do you have a general idea of what needs to be fixed?

**Comment by moollaza** [comment]
The Quickstart guide would need to be reviewed for line references and code snippets that should be updated.

**Comment by javathunderman** [comment]
@moollaza Is that it then?

**Comment by javathunderman** [comment]
@mintsoft Changed line references as noted in #215

**Comment by javathunderman** [comment]
ping @moollaza

**Comment by moollaza** [comment]
LGTM :+1:

**Pull request merged**
