### PR TITLE
asking about topics

### PR DESCRIPTION
**Pull request by zekiel**
//cc @moollaza  @talsraviv  adding a topic selection section to get a bit more personality out of PRs

### CODE REVIEW

**Comment by moollaza** [comment]
My concern with this is that to devs and myself, this seems like noise. I'm wondering if we should instead follow up with devs after merging PR's (and/or at first response) with a survey link? To gather their feedback on the process and interests, etc

**Comment by talsraviv** [comment]
I agree with @moollaza; people at this stage are so close to submitting their PR and this isn't clearly relevant. We'll probably get better quality responses if we engage them after they've achieved their goal, the good feeling of a finished contribution, and have a desire to help out DDG more.

**Comment by zekiel** [comment]
updated.

**Comment by moollaza** [comment]
LGTM :+1: 

@zekiel We'll need to update each repo's PR template with this as well.

**Pull request merged**
