### PR TITLE
Pr/208

### PR DESCRIPTION
**Pull request by moollaza**
/cc @zekiel @talsraviv

### CODE REVIEW

**Comment by moollaza** [comment]
@talsraviv you were correct about the minor merge conflict. I resolved it and this is the mergable PR.

**Comment by talsraviv** [comment]
Let me know if you need anything else from me to merge this.

**Comment by moollaza** [comment]
@talsraviv just making sure the rendering is good. So far LGTM :+1: http://moollaza.duckduckgo.com:5005/testing_triggers

**Comment by talsraviv** [comment]
Caught this - I forgot to include 'shell'
screen shot 2015-03-16 at 1 13 11 pm

**Comment by moollaza** [comment]
@talsraviv good catch! I will fix it :+1:

**Comment by talsraviv** [comment]
Odd thought that the same syntax is used in [goodie quickstart](http://moollaza.duckduckgo.com:5005/goodie_quickstart) with no ```

**Comment by moollaza** [comment]
@talsraviv should be fixed

**Comment by zekiel** [comment]
This is a great update--thanks @talsraviv and @moollaza  This will go live with the next deploy and so gets my honorary "Release" gif :) 

http://i.imgur.com/VJmxLHB.gif

**Pull request merged**
