### PR TITLE
goodie_quickstart.md: Change "let's" to "lets"

### PR DESCRIPTION
**Pull request by jagtalon**

### CODE REVIEW

**Comment by mintsoft** [comment]
nice @jagtalon

**Comment by jagtalon** [comment]
@mintsoft thanks! What do you think of the comma in `My first Goodie, it lets the world know that GitHubUsername is awesome`? I think that's a comma splice and should be something like `;` or a `.`. CC @moollaza

**Comment by mintsoft** [comment]
@jagtalon I think that should be a `;` as it's two statements in one sentence which are related.

**Comment by moollaza** [comment]
A period of semi-colon is fine. I don't care too much about which we use, or if we even change them at all :stuck_out_tongue_closed_eyes:

**Pull request merged**
