### PR TITLE
Added branches

### PR DESCRIPTION
**Pull request by gautamkrishnar**
Updated to use branches. Using of branches will allow  a contributor to do multiple contributions at same time easily,
Other pages must be updated to support branches.

### CODE REVIEW

**Comment by gautamkrishnar** [comment]
@moolaza @mintsoft What is your opinion on this?

**Comment by mintsoft** [comment]
@gautamkrishnar Whilst it's true that it's useful to create branches, it's not strictly mandatory. I would sort of say that's it's to the individual contributor to choose their workflow. That said, suggesting it as a good workflow is probably wise!

**Comment by moollaza** [comment]
@talsraviv @tagawa would like your thoughts on this. 

Branching has been an issue for many first-time devs. Not sure about the best way to go about suggesting it though. 

We obviously can't force them to use branches, but its certainly preferred that they use well-named branches for PR's so they don't run into problems with Master.

**Comment by gautamkrishnar** [comment]
I will surely update the files to make it a suggestion to the devs asap when i get some time

**Comment by talsraviv** [comment]
That's a great point. What about something like this:

"9. [Optional, best practice] Create a new branch in your repository for this particular project. This lets you work on several ideas at one time and keep them separate. Create a branch by... "

**Comment by gautamkrishnar** [comment]
@talsraviv done :smile:  :+1: 
@moollaza  I had updated the code and created another PR  #327 to support branches

**Comment by talsraviv** [comment]
LGTM :+1:

**Pull request merged**
