### PR TITLE
Small improvements to DDH menu

### PR DESCRIPTION
**Pull request by tagawa**

### CODE REVIEW

**Comment by zekiel** [comment]
thank you! :) we'll update this shortly

**Comment by tagawa** [comment]
You're welcome! Feel free to let me know if I should use a different branch structure/naming, etc.

**Comment by moollaza** [comment]
Hey @tagawa thanks a lot for doing this. However, I'm not really sure this is the best approach. I understand that you're trying to make it easier for devs to know what languages are used in each IA type, but that's not really what's most important about the IA types and I don't want people to think of them based on the language used. The most important reason for choosing your IA type is the required functionality and data source. If you're using an API you can't write a Fathead or Longtail because they're not design for that.

I think we could/should definitely specify this info somewhere, but in my opinion, the menu isn't the right place.

------

We're currently conducting a big re-write and re-organization of the docs and we'll certainly take this into consideration. I'll see if we can find a good place to put this information!

**Comment by tagawa** [comment]
Thanks for the detailed explanation @moollaza. I understand the decision and look forward to the re-organization of the docs. Sounds like a big project!

**Comment by moollaza** [comment]
@tagawa thanks a lot for understanding, and thanks again for taking the time to contribute! We really appreciate it. Feel free to stick around and comment/help on other PR's & Issues or even submit an Instant Answer!

**Comment by tagawa** [comment]
Will do. I submitted a couple of IAs a year or two ago and would like to do more.

**Comment by moollaza** [comment]
@tagawa that sounds awesome! We're always happy to see new Instant Answers :+1:

**Pull request closed without merging**
