### PR TITLE
Documentation redrafts

### PR DESCRIPTION
**Pull request by SueSmith**
Hello!

I've had a go at redrafting two docs, the welcome and development environment set-up guides. As you can see I've added a few images - they don't display at the moment because I'm on a fork, but I'm assuming you need the syntax for including the images to match the existing ones..

If there are any problems with formatting or content give me a shout - feedback appreciated!

Cheers :smiley_cat:

### CODE REVIEW

**Comment by zekiel** [comment]
Thanks, Sue--we'll take a look!

**Comment by MrChrisW** [comment]
@SueSmith This looks like a great improvement :+1: Especially like the "To get started" list :smile:

**Comment by SueSmith** [comment]
Cheers @MrChrisW :grin:

**Comment by zekiel** [comment]
We're making additional adjustments to the docs. Closing this but noting everything for a future version. 

Other updates here: https://github.com/duckduckgo/duckduckgo-documentation/pull/208/files

**Pull request closed without merging**
