### PR TITLE
Found typo in Documentation word

### PR DESCRIPTION
**Pull request by Eelviny**

### CODE REVIEW

**Comment by zekiel** [comment]
thanks @Eelviny  we're working on a new version of the docs over at https://github.com/duckduckgo/duckduckgo-documentation/pull/328  It's difficult to see the final rendering but we think the structure may be easier to use. Any feedback you have on that PR is welcome as well

**Comment by Eelviny** [comment]
Sure @zekiel , I'll go through there for grammar and mistakes if I can... I'm just guessing that this one-word change can be easily submitted to the current docs, although if you're looking to reduce the amount of merge conflicts then fair enough

**Comment by zekiel** [comment]
@Eelviny  no worries! I'm guessing we can get it in short-term //cc @moollaza  for the call

**Comment by moollaza** [comment]
LGTM :+1:

**Pull request merged**
