### PR TITLE
Adding `use strict` to IsAwesome Goodie Template

### PR DESCRIPTION
**Pull request by mintsoft**
Should force language detection as Perl 5 rather than Perl 6

### CODE REVIEW

**Comment by moollaza** [comment]
Hmm we'll need to update the docs as well before merging this. Otherwise the example and line numbers will be off. Might be better to hold off on this for now as we're currently improving the docs and re-writing them.

**Comment by mintsoft** [comment]
@moollaza that's no problem; I'll ask the users to add `use strict` in each PR for now, no biggie! 

cc @chrisjwilson

**Comment by MrChrisW** [comment]
@mintsoft Thanks for pinging me, noted :+1:

**Comment by javathunderman** [comment]
Hey, opened a similar PR in #245. I can close that one if this one is almost ready. 

@mintsoft

**Comment by mintsoft** [comment]
@javathunderman I'll close this if you're picking up the line number changes etc in #245

**Pull request closed without merging**
